<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120317192354 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE Rang (id INT AUTO_INCREMENT NOT NULL, spieler_id INT DEFAULT NULL, rang INT NOT NULL, punkte INT NOT NULL, teilnahmen INT NOT NULL, tendenz LONGTEXT NOT NULL, typ VARCHAR(255) NOT NULL, INDEX IDX_21FD0BF06EAF0EC3 (spieler_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE Rang ADD CONSTRAINT FK_21FD0BF06EAF0EC3 FOREIGN KEY (spieler_id) REFERENCES Spieler (id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE Rang");
    }
}
