<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120317185652 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE Spieler DROP FOREIGN KEY FK_FBE58E2EE342308D");
        $this->addSql("ALTER TABLE Turnier DROP FOREIGN KEY FK_A875C26A3523B2C8");
        $this->addSql("CREATE TABLE Location (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, typ VARCHAR(255) NOT NULL, beschreibung LONGTEXT DEFAULT NULL, oeffnungszeiten LONGTEXT DEFAULT NULL, adresse LONGTEXT DEFAULT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("DROP TABLE Spielstaette");
        $this->addSql("DROP TABLE Stammlokal");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE Spieler DROP FOREIGN KEY FK_FBE58E2EE342308D");
        $this->addSql("ALTER TABLE Turnier DROP FOREIGN KEY FK_A875C26A3523B2C8");
        $this->addSql("CREATE TABLE Spielstaette (id INT AUTO_INCREMENT NOT NULL, beschreibung LONGTEXT NOT NULL, oeffnungszeiten LONGTEXT NOT NULL, adresse LONGTEXT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE Stammlokal (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, typ VARCHAR(255) NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("DROP TABLE Location");
    }
}
