<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120317185915 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE Spieler ADD CONSTRAINT FK_FBE58E2EE342308D FOREIGN KEY (stammlokal_id) REFERENCES Location (id)");
        $this->addSql("ALTER TABLE Turnier ADD CONSTRAINT FK_A875C26A3523B2C8 FOREIGN KEY (spielstaette_id) REFERENCES Location (id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE Spieler DROP FOREIGN KEY FK_FBE58E2EE342308D");
        $this->addSql("ALTER TABLE Turnier DROP FOREIGN KEY FK_A875C26A3523B2C8");
    }
}
