<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120321020150 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE Rang ADD spielstaette_id INT DEFAULT NULL, ADD stammlokal_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE Rang ADD CONSTRAINT FK_21FD0BF03523B2C8 FOREIGN KEY (spielstaette_id) REFERENCES Location (id)");
        $this->addSql("ALTER TABLE Rang ADD CONSTRAINT FK_21FD0BF0E342308D FOREIGN KEY (stammlokal_id) REFERENCES Location (id)");
        $this->addSql("CREATE INDEX IDX_21FD0BF03523B2C8 ON Rang (spielstaette_id)");
        $this->addSql("CREATE INDEX IDX_21FD0BF0E342308D ON Rang (stammlokal_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE Rang DROP FOREIGN KEY FK_21FD0BF03523B2C8");
        $this->addSql("ALTER TABLE Rang DROP FOREIGN KEY FK_21FD0BF0E342308D");
        $this->addSql("DROP INDEX IDX_21FD0BF03523B2C8 ON Rang");
        $this->addSql("DROP INDEX IDX_21FD0BF0E342308D ON Rang");
        $this->addSql("ALTER TABLE Rang DROP spielstaette_id, DROP stammlokal_id");
    }
}
